enyo.depends(
	"$/preferences.js",
	"$/storage.js",	
	"$/app.js",
	"$/articles.js",
	"$/article_detail.js",	
	"$/matchs.js",
	"$/match_detail.js",
	"$/classements.js",
	"$/equipe.js",
	"$/equipe_matchs.js",
	"$/favoris.js",
	"$/history.js",
	"$/cached_jsonp.js",
	"$/analytics.js"
);